// Code generated by mockery v1.0.0. DO NOT EDIT.
package boltdb

import bolt "github.com/boltdb/bolt"

import mock "github.com/stretchr/testify/mock"

// Transaction is an autogenerated mock type for the Transaction type
type Transaction struct {
	mock.Mock
}

// Bucket provides a mock function with given fields: _a0
func (_m *Transaction) Bucket(_a0 []byte) *bolt.Bucket {
	ret := _m.Called(_a0)

	var r0 *bolt.Bucket
	if rf, ok := ret.Get(0).(func([]byte) *bolt.Bucket); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bolt.Bucket)
		}
	}

	return r0
}

// CreateBucket provides a mock function with given fields: _a0
func (_m *Transaction) CreateBucket(_a0 []byte) (*bolt.Bucket, error) {
	ret := _m.Called(_a0)

	var r0 *bolt.Bucket
	if rf, ok := ret.Get(0).(func([]byte) *bolt.Bucket); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bolt.Bucket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
