// Code generated by mockery v1.0.0. DO NOT EDIT.
package service

import mock "github.com/stretchr/testify/mock"
import service "github.com/rodrigodiez/zorro/pkg/service"

// Zorro is an autogenerated mock type for the Zorro type
type Zorro struct {
	mock.Mock
}

// Mask provides a mock function with given fields: key
func (_m *Zorro) Mask(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Unmask provides a mock function with given fields: value
func (_m *Zorro) Unmask(value string) (string, bool) {
	ret := _m.Called(value)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// WithMetrics provides a mock function with given fields: _a0
func (_m *Zorro) WithMetrics(_a0 *service.Metrics) service.Zorro {
	ret := _m.Called(_a0)

	var r0 service.Zorro
	if rf, ok := ret.Get(0).(func(*service.Metrics) service.Zorro); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Zorro)
		}
	}

	return r0
}
