// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// Counter is an autogenerated mock type for the Counter type
type Counter struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *Counter) Add(_a0 int64) {
	_m.Called(_a0)
}
