// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// IntCounter is an autogenerated mock type for the IntCounter type
type IntCounter struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *IntCounter) Add(_a0 int64) {
	_m.Called(_a0)
}
