// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// LoadOrStore provides a mock function with given fields: id, mask
func (_m *Storage) LoadOrStore(id string, mask string) (string, bool) {
	ret := _m.Called(id, mask)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(id, mask)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = rf(id, mask)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Resolve provides a mock function with given fields: mask
func (_m *Storage) Resolve(mask string) (string, bool) {
	ret := _m.Called(mask)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(mask)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(mask)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
