// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// Zorro is an autogenerated mock type for the Zorro type
type Zorro struct {
	mock.Mock
}

// Mask provides a mock function with given fields: id
func (_m *Zorro) Mask(id string) string {
	ret := _m.Called(id)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Unmask provides a mock function with given fields: mask
func (_m *Zorro) Unmask(mask string) (string, bool) {
	ret := _m.Called(mask)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(mask)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(mask)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
